# Statistcs

2 Types, descriptive and inferential statistics

In [10]:
#Descriptive Statistics 
#In measure of central tendency
#mean, median, mode

# Measure of central tendency

1. Mean
2. Median 
3. Mode

Example 1,
Example 2,
Example 3,
Example 4,
Example 5,
Example 6,
Example 7,
Example 8

# Example 1

In [11]:
#Example 1
#mean 

import numpy as np
X=[1,1,2,2,3,3,4,5,5,6]

#using numpy
np.mean(X)

3.2

In [12]:
print("mean:",np.mean(X))

mean: 3.2


In [13]:
#created the list into a table format
import pandas as pd
y=pd.DataFrame(data={'value':[1,1,2,2,3,3,4,5,5,6]})
y

value
0      1
1      1
2      2
3      2
4      3
5      3
6      4
7      5
8      5
9      6

In [14]:
#mean using pandas
y.mean()


value    3.2
dtype: float64

In [15]:
y.describe()

value
count  10.00000
mean    3.20000
std     1.75119
min     1.00000
25%     2.00000
50%     3.00000
75%     4.75000
max     6.00000

In [17]:
#median
X=[1,1,2,2,3,3,4,5,5,6]

#using numpy
np.median(X)

3.0

In [18]:
print("median:",np.median(X))

median: 3.0


In [19]:
#using pandas
y.median()

value    3.0
dtype: float64

In [20]:
y.describe()

value
count  10.00000
mean    3.20000
std     1.75119
min     1.00000
25%     2.00000
50%     3.00000
75%     4.75000
max     6.00000

In [ ]:
#mode
#numpy does not has an attribute mode

In [21]:
#using pandas
y.mode()

value
0      1
1      2
2      3
3      5

In [ ]:
#descriptive statistics
#measure of dispersion
#variance and std deviation

# Measure of Dispersion

In [23]:
#variance
X=[1,1,2,2,3,3,4,5,5,6]

#using numpy
np.var(X)

2.7600000000000002

In [24]:
print("Variance : ", np.var(X))

Variance :  2.7600000000000002


In [25]:
#using pandas
y.var()    

value    3.066667
dtype: float64

In [26]:
#standard deviation
X=[1,1,2,2,3,3,4,5,5,6]

#using numpy
np.std(X)

1.661324772583615

In [27]:
print("Variance : ", np.std(X))

Variance :  1.661324772583615


In [28]:
#using pandas
y.std() 

value    1.75119
dtype: float64

# 5 Number Summary

Minimum,
1st quartile -Q1,
2nd quartile -Q2(Median),
3rd quartile -Q3,
Maximum

In [29]:
#Minimum
X=[1,1,2,2,3,3,4,5,5,6]

#using numpy
np.min(X)

1

In [30]:
print("Minimum : ", np.min(X))

Minimum :  1


In [31]:
#using pandas
y.min()

value    1
dtype: int64

In [32]:
#quartiles
X=[1,1,2,2,3,3,4,5,5,6]

#using numpy
np.quantile(X,[0.25,0.50,0.75])

array([2.  , 3.  , 4.75])

In [33]:
print("Q1 : ", np.quantile(X,0.25),
      "Q2 : ", np.quantile(X,0.50),
      "Q3 : ", np.quantile(X,0.75))

Q1 :  2.0 Q2 :  3.0 Q3 :  4.75


In [34]:
#using pandas
y.quantile([0.25,0.50,0.75]) 

value
0.25   2.00
0.50   3.00
0.75   4.75

In [35]:
y.describe()

value
count  10.00000
mean    3.20000
std     1.75119
min     1.00000
25%     2.00000
50%     3.00000
75%     4.75000
max     6.00000

In [36]:
#Maximum
X=[1,1,2,2,3,3,4,5,5,6]

#using numpy
np.max(X)

6

In [37]:
print("Maximum : ", np.max(X))

Maximum :  6


In [38]:
#using pandas
y.max() 

value    6
dtype: int64

# Range

In [39]:
#Range
#using numpy

Ran=np.max(X) - np.min(X)
Ran

5

In [41]:
#using pandas
Range = y.max()-y.min()
Range

value    5
dtype: int64

# IQR

In [44]:
#IQR
#using numpy
IQR = np.quantile(X,0.75)-np.quantile(X,0.25)
IQR

2.75

In [45]:
#using pandas
iqr=y.quantile(0.75)-y.quantile(0.25)
iqr
     

value    2.75
dtype: float64

# QD

In [46]:
#QD
#using numpy
QD = IQR/2
QD

1.375

In [47]:
#QD
#using pandas
qd =iqr/2
qd
     

value    1.375
dtype: float64

# Example 2

In [48]:
#Example 2
#mean

import numpy as pd
X=[1,1,2,2,3,3,4,5,5,6,100,112]

#using numpy
np.mean(X)

20.333333333333332

In [49]:
print("mean : ", np.mean(X))

mean :  20.333333333333332


In [50]:
#created the list into a table format
import pandas as pd
j=pd.DataFrame(data={'values': [1,1,2,2,3,3,4,5,5,6,100,112]})
j

values
0        1
1        1
2        2
3        2
4        3
5        3
6        4
7        5
8        5
9        6
10     100
11     112

In [51]:
#mean using pandas
j.mean()

values    20.333333
dtype: float64

In [52]:
y.describe()

value
count  10.00000
mean    3.20000
std     1.75119
min     1.00000
25%     2.00000
50%     3.00000
75%     4.75000
max     6.00000

In [53]:
#median
X=[1,1,2,2,3,3,4,5,5,6,100,112]

#using numpy
np.median(X)

3.5

In [54]:
print("median : ", np.median(X))

median :  3.5


In [55]:
j.describe()

values
count   12.000000
mean    20.333333
std     40.127826
min      1.000000
25%      2.000000
50%      3.500000
75%      5.250000
max    112.000000

In [ ]:
#mode
#numpy does not has an attribute mode

In [56]:
#using pandas
j.mode() 

values
0       1
1       2
2       3
3       5

# Measure of Dispersion

In [57]:
#variance
X=[1,1,2,2,3,3,4,5,5,6,100,112]

#using numpy
np.var(X)

1476.0555555555557

In [58]:

print("Variance : ", np.var(X))

Variance :  1476.0555555555557


In [59]:
#using pandas
j.var() 

values    1610.242424
dtype: float64

In [61]:
#standard deviation
X=[1,1,2,2,3,3,4,5,5,6,100,112]

#using numpy
np.std(X)

38.41946844446908

In [62]:
print("Variance : ", np.std(X))


Variance :  38.41946844446908


In [63]:
#using pandas
j.std() 

values    40.127826
dtype: float64

# 5 Number Summary

Minimum,
1st quartile -Q1,
2nd quartile -Q2(Median),
3rd quartile -Q3,
Maximum

In [65]:
#Minimum
X=[1,1,2,2,3,3,4,5,5,6,100,112]

#using numpy
np.min(X)
     

1

In [66]:
print("Minimum : ", np.min(X))

Minimum :  1


In [67]:
#using pandas
y.min() 

value    1
dtype: int64

In [68]:
#quartiles
X=[1,1,2,2,3,3,4,5,5,6,100,112]

#using numpy
np.quantile(X,[0.25,0.50,0.75])

array([2.  , 3.5 , 5.25])

In [69]:
print("Q1 : ", np.quantile(X,0.25),
      "Q2 : ", np.quantile(X,0.50),
      "Q3 : ", np.quantile(X,0.75))

Q1 :  2.0 Q2 :  3.5 Q3 :  5.25


In [71]:
#using pandas
j.quantile([0.25,0.50,0.75])  

values
0.25    2.00
0.50    3.50
0.75    5.25

In [72]:
#using pandas
j.quantile([0.25,0.50,0.75])  

values
0.25    2.00
0.50    3.50
0.75    5.25

In [73]:
#Maximum
X=[1,1,2,2,3,3,4,5,5,6,100,112]

#using numpy
np.max(X)

112

In [74]:
print("Maximum : ", np.max(X))

Maximum :  112


In [75]:
#using pandas
j.max()          

values    112
dtype: int64

# Range

In [76]:
#Range
#using numpy

Ran=np.max(X) - np.min(X)
Ran
     

111

In [77]:
#using pandas
Range = j.max()-j.min()
Range

values    111
dtype: int64

# IQR

In [78]:
#IQR
#using numpy
IQR = np.quantile(X,0.75)-np.quantile(X,0.25)
IQR

3.25

In [79]:
#using pandas
iqr=j.quantile(0.75)-j.quantile(0.25)
iqr
     

values    3.25
dtype: float64

# QD

In [80]:
#QD
#using numpy
QD = IQR/2
QD

1.625

In [81]:
#QD
#using pandas
qd =iqr/2
qd

values    1.625
dtype: float64

# Example 3

In [82]:
#Example 3
#mean 

import numpy as np
X=[1,2,2,3,4,5,6,6,6,7,8,100,200]

#using numpy
np.mean(X)

26.923076923076923

In [83]:
print("mean : ", np.mean(X))

mean :  26.923076923076923


In [84]:
#created the list into a table format
import pandas as pd
k=pd.DataFrame(data={'values': [1,2,2,3,4,5,6,6,6,7,8,100,200]})
k

values
0        1
1        2
2        2
3        3
4        4
5        5
6        6
7        6
8        6
9        7
10       8
11     100
12     200

In [85]:
#mean using pandas
k.mean()

values    26.923077
dtype: float64

In [86]:
k.describe()

values
count   13.000000
mean    26.923077
std     58.350181
min      1.000000
25%      3.000000
50%      6.000000
75%      7.000000
max    200.000000

In [87]:
#median
X=[1,2,2,3,4,5,6,6,6,7,8,100,200]

#using numpy
np.median(X)

6.0

In [88]:
print("median : ", np.median(X))

median :  6.0


In [89]:
#using pandas
k.median()

values    6.0
dtype: float64

In [90]:

k.describe()

values
count   13.000000
mean    26.923077
std     58.350181
min      1.000000
25%      3.000000
50%      6.000000
75%      7.000000
max    200.000000

In [ ]:
#mode
#numpy does not has an attribute mode

In [91]:
#using pandas
k.mode()    
     

values
0       6

# Measure of Dispersion

In [92]:
#variance
X=[1,2,2,3,4,5,6,6,6,7,8,100,200]

#using numpy
np.var(X)

3142.84023668639

In [93]:
print("Variance : ", np.var(X))

Variance :  3142.84023668639


In [94]:
#using pandas
k.var() 

values    3404.74359
dtype: float64

In [96]:
#standard deviation
X=[1,2,2,3,4,5,6,6,6,7,8,100,200]

#using numpy
np.std(X)

56.0610402747433

In [97]:

print("Variance : ", np.std(X))

Variance :  56.0610402747433


In [98]:
#using pandas
k.std()

values    58.350181
dtype: float64

# 5 Number Summary

1.Minimum
2.1st quartile -Q1
3.2nd quartile -Q2(Median)
4.3rd quartile -Q3
5.Maximum

In [100]:
#Minimum
X=[1,2,2,3,4,5,6,6,6,7,8,100,200]

#using numpy
np.min(X)

1

In [101]:
print("Minimum : ", np.min(X))

Minimum :  1


In [102]:
#using pandas
k.min() 

values    1
dtype: int64

In [103]:
#quartiles
X=[1,2,2,3,4,5,6,6,6,7,8,100,200]

#using numpy
np.quantile(X,[0.25,0.50,0.75])
     

array([3., 6., 7.])

In [104]:
print("Q1 : ", np.quantile(X,0.25),
      "Q2 : ", np.quantile(X,0.50),
      "Q3 : ", np.quantile(X,0.75))
     

Q1 :  3.0 Q2 :  6.0 Q3 :  7.0


In [105]:
#using pandas
k.quantile([0.25,0.50,0.75])

values
0.25     3.0
0.50     6.0
0.75     7.0

In [106]:

k.describe()

values
count   13.000000
mean    26.923077
std     58.350181
min      1.000000
25%      3.000000
50%      6.000000
75%      7.000000
max    200.000000

In [107]:
#Maximum
X=[1,2,2,3,4,5,6,6,6,7,8,100,200]

#using numpy
np.max(X)
     

200

In [108]:
print("Maximum : ", np.max(X))

Maximum :  200


In [109]:
#using pandas
k.max()          
     

values    200
dtype: int64

# Range

In [110]:
#Range
#using numpy

Ran=np.max(X) - np.min(X)
Ran

199

In [111]:
#using pandas
Range = k.max()-k.min()
Range

values    199
dtype: int64

# IQR

In [112]:
#IQR
#using numpy
IQR = np.quantile(X,0.75)-np.quantile(X,0.25)
IQR

4.0

In [113]:
#using pandas
iqr=k.quantile(0.75)-k.quantile(0.25)
iqr
     

values    4.0
dtype: float64

# QD

In [114]:
#QD
#using numpy
QD = IQR/2
QD

2.0

In [115]:
#QD
#using pandas
qd =iqr/2
qd
     

values    2.0
dtype: float64

# Example 4

In [116]:
#Example 4
#mean 

import numpy as np
X=[1,2,2,3,4,5,6,6,6,7,8,100,200,5000]

#using numpy
np.mean(X)

382.14285714285717

In [117]:
#created the list into a table format
import pandas as pd
b=pd.DataFrame(data={'values': [1,2,2,3,4,5,6,6,6,7,8,100,200,5000]})
b

values
0        1
1        2
2        2
3        3
4        4
5        5
6        6
7        6
8        6
9        7
10       8
11     100
12     200
13    5000

In [118]:
#mean using pandas
b.mean()

values    382.142857
dtype: float64

In [119]:

b.describe()

values
count    14.000000
mean    382.142857
std    1330.292499
min       1.000000
25%       3.250000
50%       6.000000
75%       7.750000
max    5000.000000

In [120]:
#median
X=[1,2,2,3,4,5,6,6,6,7,8,100,200,5000]

#using numpy
np.median(X)

6.0

In [121]:
print("median : ", np.median(X))

median :  6.0


In [122]:
#using pandas
b.median()
     

values    6.0
dtype: float64

In [123]:
b.describe()

values
count    14.000000
mean    382.142857
std    1330.292499
min       1.000000
25%       3.250000
50%       6.000000
75%       7.750000
max    5000.000000

In [ ]:
#mode
#numpy does not has an attribute mode

In [124]:
#using pandas
b.mode() 

values
0       6

# Measure of Dispersion

In [125]:
#variance
X=[1,2,2,3,4,5,6,6,6,7,8,100,200,5000]

#using numpy
np.var(X)

1643272.5510204083

In [126]:
print("Variance : ", np.var(X))

Variance :  1643272.5510204083


In [127]:
#using pandas
b.var()          
     

values    1.769678e+06
dtype: float64

In [128]:
#standard deviation
X=[1,2,2,3,4,5,6,6,6,7,8,100,200,5000]

#using numpy
np.std(X)

1281.9019272239232

In [129]:
print("Variance : ", np.std(X))

Variance :  1281.9019272239232


In [130]:
#using pandas
b.std() 

values    1330.292499
dtype: float64

# 5 Number summary

Minimum,
1st quartile -Q1,
2nd quartile -Q2(Median),
3rd quartile -Q3,
Maximum

In [132]:
#Minimum
X=[1,2,2,3,4,5,6,6,6,7,8,100,200,5000]

#using numpy
np.min(X)

1

In [133]:
print("Minimum : ", np.min(X))


Minimum :  1


In [134]:
#using pandas
b.min() 

values    1
dtype: int64

In [135]:
#quartiles
X=[1,2,2,3,4,5,6,6,6,7,8,100,200,5000]

#using numpy
np.quantile(X,[0.25,0.50,0.75])

array([3.25, 6.  , 7.75])

In [136]:
print("Q1 : ", np.quantile(X,0.25),
      "Q2 : ", np.quantile(X,0.50),
      "Q3 : ", np.quantile(X,0.75))

Q1 :  3.25 Q2 :  6.0 Q3 :  7.75


In [137]:
#using pandas
b.quantile([0.25,0.50,0.75])          

values
0.25    3.25
0.50    6.00
0.75    7.75

In [138]:
b.describe()

values
count    14.000000
mean    382.142857
std    1330.292499
min       1.000000
25%       3.250000
50%       6.000000
75%       7.750000
max    5000.000000

In [139]:
#Maximum
X=[1,2,2,3,4,5,6,6,6,7,8,100,200,5000]

#using numpy
np.max(X)

5000

In [140]:
print("Maximum : ", np.max(X))

Maximum :  5000


In [141]:
#using pandas
b.max()

values    5000
dtype: int64

# Range

In [142]:
#Range
#using numpy

Ran=np.max(X) - np.min(X)
Ran

4999

In [143]:
#using pandas
Range = b.max()-b.min()
Range
     

values    4999
dtype: int64

# IQR

In [144]:
#IQR
#using numpy
IQR = np.quantile(X,0.75)-np.quantile(X,0.25)
IQR

4.5

In [145]:
#using pandas
iqr=b.quantile(0.75)-b.quantile(0.25)
iqr

values    4.5
dtype: float64

# QD

In [146]:
#QD
#using numpy
QD = IQR/2
QD

2.25

In [147]:
#QD
#using pandas
qd =iqr/2
qd

values    2.25
dtype: float64

# Example 5

In [153]:
#mean
#Example 5

import numpy as np
X=[1,1,2,2,4]


#using numpy
np.mean(X)

2.0

In [154]:
print("mean : ", np.mean(X))

mean :  2.0


In [157]:
#created the list into a table format
import pandas as pd
e=pd.DataFrame(data={'values': [1,1,2,2,4]})
e

values
0       1
1       1
2       2
3       2
4       4

In [158]:
#mean using pandas
e.mean()

values    2.0
dtype: float64

In [159]:

e.describe()

values
count  5.000000
mean   2.000000
std    1.224745
min    1.000000
25%    1.000000
50%    2.000000
75%    2.000000
max    4.000000

In [160]:
#median
X=[1,1,2,2,4]

#using numpy
np.median(X)

2.0

In [161]:
print("median : ", np.median(X))

median :  2.0


In [162]:
#using pandas
e.median()
     

values    2.0
dtype: float64

In [163]:

e.describe()

values
count  5.000000
mean   2.000000
std    1.224745
min    1.000000
25%    1.000000
50%    2.000000
75%    2.000000
max    4.000000

In [ ]:
#mode
#numpy does not has an attribute mode
     

In [164]:
#using pandas
e.mode()

values
0       1
1       2

# Measure of Dispersion

In [165]:
#variance
X=[1,1,2,2,4]

#using numpy
np.var(X)

1.2

In [166]:
print("Variance : ", np.var(X))

Variance :  1.2


In [167]:
#using pandas
e.var()   

values    1.5
dtype: float64

In [168]:
#standard deviation
X=[1,1,2,2,4]

#using numpy
np.std(X)

1.0954451150103321

In [169]:
print("Variance : ", np.std(X))

Variance :  1.0954451150103321


In [170]:
#using pandas
e.std()

values    1.224745
dtype: float64

# 5 Number Summary

Minimum,
1st quartile -Q1,
2nd quartile -Q2(Median),
3rd quartile -Q3,
Maximum

In [172]:
#Minimum
X=[1,1,2,2,4]

#using numpy
np.min(X)

1

In [173]:
print("Minimum : ", np.min(X))
     

Minimum :  1


In [174]:
#using pandas
e.min()  

values    1
dtype: int64

In [175]:
#quartiles
X=[1,1,2,2,4]

#using numpy
np.quantile(X,[0.25,0.50,0.75])

array([1., 2., 2.])

In [176]:
print("Q1 : ", np.quantile(X,0.25),
      "Q2 : ", np.quantile(X,0.50),
      "Q3 : ", np.quantile(X,0.75))

Q1 :  1.0 Q2 :  2.0 Q3 :  2.0


In [177]:
#using pandas
e.quantile([0.25,0.50,0.75])          
     

values
0.25     1.0
0.50     2.0
0.75     2.0

In [178]:
e.describe()

values
count  5.000000
mean   2.000000
std    1.224745
min    1.000000
25%    1.000000
50%    2.000000
75%    2.000000
max    4.000000

In [179]:
#Maximum
X=[1,1,2,2,4]

#using numpy
np.max(X)

4

In [180]:
print("Maximum : ", np.max(X))

Maximum :  4


In [181]:
#using pandas
e.max()    

values    4
dtype: int64

# Range

In [182]:
#Range
#using numpy

Ran=np.max(X) - np.min(X)
Ran

3

In [183]:
#using pandas
Range = e.max()-e.min()
Range

values    3
dtype: int64

# IQR

In [184]:
#IQR
#using numpy
IQR = np.quantile(X,0.75)-np.quantile(X,0.25)
IQR
     

1.0

In [185]:
#using pandas
iqr=e.quantile(0.75)-e.quantile(0.25)
iqr

values    1.0
dtype: float64

# QD

In [186]:
#QD
#using numpy
QD = IQR/2
QD

0.5

In [187]:
#QD
#using pandas
qd =iqr/2
qd
     

values    0.5
dtype: float64

# Example 6

In [188]:
#Example 6
#mean 

import numpy as np
X=[2,2,2,2,2]

#using numpy
np.mean(X)

2.0

In [189]:
print("mean : ", np.mean(X))

mean :  2.0


In [190]:
#created the list into a table format
import pandas as pd
g=pd.DataFrame(data={'values': [2,2,2,2,2]})
g


values
0       2
1       2
2       2
3       2
4       2

In [191]:
#mean using pandas
g.mean()
     

values    2.0
dtype: float64

In [192]:

g.describe()

values
count     5.0
mean      2.0
std       0.0
min       2.0
25%       2.0
50%       2.0
75%       2.0
max       2.0

In [193]:
#median
X=[2,2,2,2,2]

#using numpy
np.median(X)

2.0

In [194]:
print("median : ", np.median(X))

median :  2.0


In [195]:
#using pandas
g.median()

values    2.0
dtype: float64

In [196]:

g.describe()

values
count     5.0
mean      2.0
std       0.0
min       2.0
25%       2.0
50%       2.0
75%       2.0
max       2.0

In [ ]:
#mode
#numpy does not has an attribute mode

In [197]:
#using pandas
g.mode()    
     

values
0       2

# Measure of Dispersion

In [198]:
#variance
X=[2,2,2,2,2]

#using numpy
np.var(X)

0.0

In [199]:
print("Variance : ", np.var(X))

Variance :  0.0


In [200]:
#using pandas
g.var()   

values    0.0
dtype: float64

In [201]:
#standard deviation
X=[2,2,2,2,2]

#using numpy
np.std(X)

0.0

In [202]:

print("Variance : ", np.std(X))

Variance :  0.0


In [203]:

#using pandas
g.std() 

values    0.0
dtype: float64

# 5 Number Summary

Minimum,
1st quartile -Q1,
2nd quartile -Q2(Median),
3rd quartile -Q3,
Maximum

In [205]:
#Minimum
X=[2,2,2,2,2]

#using numpy
np.min(X)

2

In [206]:
#using pandas
g.min() 

values    2
dtype: int64

In [207]:
#quartiles
X=[2,2,2,2,2]

#using numpy
np.quantile(X,[0.25,0.50,0.75])
     

array([2., 2., 2.])

In [208]:
print("Q1 : ", np.quantile(X,0.25),
      "Q2 : ", np.quantile(X,0.50),
      "Q3 : ", np.quantile(X,0.75))

Q1 :  2.0 Q2 :  2.0 Q3 :  2.0


In [209]:
#using pandas
g.quantile([0.25,0.50,0.75])          
     

values
0.25     2.0
0.50     2.0
0.75     2.0

In [210]:

g.describe()

values
count     5.0
mean      2.0
std       0.0
min       2.0
25%       2.0
50%       2.0
75%       2.0
max       2.0

In [211]:
#Maximum
X=[2,2,2,2,2]

#using numpy
np.max(X)

2

In [212]:

print("Maximum : ", np.max(X))

Maximum :  2


In [213]:
#using pandas
g.max()          
     

values    2
dtype: int64

# Range

In [214]:
#Range
#using numpy

Ran=np.max(X) - np.min(X)
Ran

0

In [215]:
#using pandas
Range =g.max()-g.min()
Range

values    0
dtype: int64

# IQR

In [216]:
#IQR
#using numpy
IQR = np.quantile(X,0.75)-np.quantile(X,0.25)
IQR
     

0.0

In [217]:
#using pandas
iqr=g.quantile(0.75)-g.quantile(0.25)
iqr

values    0.0
dtype: float64

# QD

In [218]:
#QD
#using numpy
QD = IQR/2
QD

0.0

In [219]:
#QD
#using pandas
qd =iqr/2
qd

values    0.0
dtype: float64

# Example 7

In [220]:
#mean 

import numpy as np
X=[2,2,2,2,2,10000]

#using numpy
np.mean(X)
     

1668.3333333333333

In [221]:

print("mean : ", np.mean(X))

mean :  1668.3333333333333


In [222]:
#created the list into a table format
import pandas as pd
q=pd.DataFrame(data={'values': [2,2,2,2,2,10000]})
q

values
0       2
1       2
2       2
3       2
4       2
5   10000

In [223]:
#mean using pandas
q.mean()

values    1668.333333
dtype: float64

In [224]:
q.describe()

values
count      6.000000
mean    1668.333333
std     4081.666408
min        2.000000
25%        2.000000
50%        2.000000
75%        2.000000
max    10000.000000

In [225]:
#median
X=[2,2,2,2,2,10000]

#using numpy
np.median(X)

2.0

In [226]:
print("median : ", np.median(X))

median :  2.0


In [227]:
#using pandas
g.median()

values    2.0
dtype: float64

In [228]:
g.describe()

values
count     5.0
mean      2.0
std       0.0
min       2.0
25%       2.0
50%       2.0
75%       2.0
max       2.0

In [ ]:
#mode
#numpy does not has an attribute mode
     

In [229]:
#using pandas
q.mode()

values
0       2

# Measure of Dispersion

In [230]:
#variance
X=[2,2,2,2,2,10000]

#using numpy
np.var(X)

13883333.888888886

In [231]:
print("Variance : ", np.var(X))

Variance :  13883333.888888886


In [232]:
#using pandas
q.var() 

values    1.666000e+07
dtype: float64

In [233]:
#standard deviation
X=[2,2,2,2,2,10000]

#using numpy
np.std(X)

3726.0346065071494

In [234]:
print("Variance : ", np.std(X))

Variance :  3726.0346065071494


In [235]:
#using pandas
q.std()

values    4081.666408
dtype: float64

# 5 Number Summary

Minimum,
1st quartile -Q1,
2nd quartile -Q2(Median),
3rd quartile -Q3,
Maximum


In [236]:
#Minimum
X=[2,2,2,2,2,10000]

#using numpy
np.min(X)

2

In [237]:
print("Minimum : ", np.min(X))

Minimum :  2


In [238]:
#using pandas
q.min()  

values    2
dtype: int64

In [239]:
#quartiles
X=[2,2,2,2,2,10000]

#using numpy
np.quantile(X,[0.25,0.50,0.75])

array([2., 2., 2.])

In [240]:
print("Q1 : ", np.quantile(X,0.25),
      "Q2 : ", np.quantile(X,0.50),
      "Q3 : ", np.quantile(X,0.75))

Q1 :  2.0 Q2 :  2.0 Q3 :  2.0


In [241]:
#using pandas
q.quantile([0.25,0.50,0.75])          
     

values
0.25     2.0
0.50     2.0
0.75     2.0

In [242]:
q.describe()

values
count      6.000000
mean    1668.333333
std     4081.666408
min        2.000000
25%        2.000000
50%        2.000000
75%        2.000000
max    10000.000000

In [243]:
#Maximum
X=[2,2,2,2,2,10000]

#using numpy
np.max(X)
     

10000

In [244]:
print("Maximum : ", np.max(X))
     

Maximum :  10000


In [245]:
#using pandas
q.max()  

values    10000
dtype: int64

# Range

In [246]:
#Range
#using numpy

Ran=np.max(X) - np.min(X)
Ran

9998

In [247]:
#using pandas
Range = q.max()-q.min()
Range

values    9998
dtype: int64

# IQR 

In [248]:
#IQR
#using numpy
IQR = np.quantile(X,0.75)-np.quantile(X,0.25)
IQR

0.0

In [249]:
#using pandas
iqr=q.quantile(0.75)-q.quantile(0.25)
iqr
     

values    0.0
dtype: float64

# QD

In [250]:
#QD
#using numpy
QD = IQR/2
QD

0.0

In [251]:
#QD
#using pandas
qd =iqr/2
qd

values    0.0
dtype: float64

# Example 8

In [252]:
#mean 

import numpy as np
X=[1,1,2,2,3,3,4,5,5,6,100]

#using numpy
np.mean(X)

12.0

In [253]:
print("mean : ", np.mean(X))

mean :  12.0


In [254]:
#created the list into a table format
import pandas as pd
r=pd.DataFrame(data={'values': [1,1,2,2,3,3,4,5,5,6,100]})
r

values
0        1
1        1
2        2
3        2
4        3
5        3
6        4
7        5
8        5
9        6
10     100

In [255]:
#mean using pandas
r.mean()
     

values    12.0
dtype: float64

In [256]:
r.describe()

values
count   11.000000
mean    12.000000
std     29.233542
min      1.000000
25%      2.000000
50%      3.000000
75%      5.000000
max    100.000000

In [257]:
#median
X=[1,1,2,2,3,3,4,5,5,6,100]

#using numpy
np.median(X)

3.0

In [258]:
print("median : ", np.median(X))

median :  3.0


In [259]:
#using pandas
r.median()

values    3.0
dtype: float64

In [260]:
r.describe()

values
count   11.000000
mean    12.000000
std     29.233542
min      1.000000
25%      2.000000
50%      3.000000
75%      5.000000
max    100.000000

In [ ]:
#mode
#numpy does not has an attribute mode    

In [261]:
#using pandas
r.mode()   

values
0       1
1       2
2       3
3       5

# Measure of Dispersion

In [262]:
#variance
X=[1,1,2,2,3,3,4,5,5,6,100]

#using numpy
np.var(X)

776.9090909090909

In [263]:
print("Variance : ", np.var(X))

Variance :  776.9090909090909


In [264]:
#using pandas
r.var() 

values    854.6
dtype: float64

In [265]:
#standard deviation
X=[1,1,2,2,3,3,4,5,5,6,100]

#using numpy
np.std(X)

27.873089009097843

In [266]:
print("Variance : ", np.std(X))

Variance :  27.873089009097843


In [267]:
#using pandas
r.std()

values    29.233542
dtype: float64

# 5 Number Summary

Minimum,
1st quartile -Q1,
2nd quartile -Q2(Median),
3rd quartile -Q3,
Maximum

In [268]:
#Minimum
X=[1,1,2,2,3,3,4,5,5,6,100]

#using numpy
np.min(X)

1

In [269]:
print("Minimum : ", np.min(X))

Minimum :  1


In [270]:
#using pandas
r.min()  

values    1
dtype: int64

In [271]:
#quartiles
X=[1,1,2,2,3,3,4,5,5,6,100]

#using numpy
np.quantile(X,[0.25,0.50,0.75])   

array([2., 3., 5.])

In [272]:
print("Q1 : ", np.quantile(X,0.25),
      "Q2 : ", np.quantile(X,0.50),
      "Q3 : ", np.quantile(X,0.75))

Q1 :  2.0 Q2 :  3.0 Q3 :  5.0


In [273]:
#using pandas
r.quantile([0.25,0.50,0.75])        

values
0.25     2.0
0.50     3.0
0.75     5.0

In [274]:
r.describe()

values
count   11.000000
mean    12.000000
std     29.233542
min      1.000000
25%      2.000000
50%      3.000000
75%      5.000000
max    100.000000

In [275]:
#Maximum
X=[1,1,2,2,3,3,4,5,5,6,100]

#using numpy
np.max(X)

100

In [276]:
print("Maximum : ", np.max(X))

Maximum :  100


In [277]:
#using pandas
r.max()   

values    100
dtype: int64

# Range

In [278]:
#Range
#using numpy

Ran=np.max(X) - np.min(X)
Ran

99

In [279]:
#using pandas
Range = r.max()-r.min()
Range

values    99
dtype: int64

# IQR

In [280]:
#IQR
#using numpy
IQR = np.quantile(X,0.75)-np.quantile(X,0.25)
IQR

3.0

In [281]:
#using pandas
iqr=r.quantile(0.75)-r.quantile(0.25)
iqr

values    3.0
dtype: float64

# QD

In [282]:
#QD
#using numpy
QD = IQR/2
QD

1.5

In [283]:
#QD
#using pandas
qd =iqr/2
qd

values    1.5
dtype: float64